# Generated by Django 3.0.7 on 2020-06-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('product_id', models.IntegerField(db_index=True)),
                ('recipe', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('inspected', models.IntegerField()),
                ('accepted', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('technical_rejects', models.IntegerField()),
            ],
        ),
    ]
