# Generated by Django 3.0.7 on 2020-06-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ampoule',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('product_id', models.IntegerField(db_index=True)),
                ('recipe', models.CharField(max_length=255)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('end_date', models.DateTimeField()),
                ('inspected', models.IntegerField()),
                ('accepted', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('technical_rejects', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AmpouleAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('time_stamp', models.DateTimeField(db_index=True)),
                ('delta_to_utc', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=555, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('check_sum', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vial',
            fields=[
                ('username', models.CharField(max_length=255)),
                ('product_id', models.IntegerField(db_index=True)),
                ('recipe', models.CharField(max_length=255)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(primary_key=True, serialize=False)),
                ('end_date', models.DateTimeField()),
                ('inspected', models.IntegerField()),
                ('accepted', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('technical_rejects', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VialAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.IntegerField()),
                ('time_stamp', models.DateTimeField(db_index=True)),
                ('delta_to_utc', models.CharField(blank=True, max_length=255, null=True)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=555, null=True)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('check_sum', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
