# Generated by Django 3.0.7 on 2020-06-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vial',
            name='batch',
        ),
        migrations.AddField(
            model_name='vial',
            name='batch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vial',
            name='batch_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
