# Generated by Django 3.0.7 on 2020-07-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampoule',
            name='st0_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vial',
            name='st0_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
