# Generated by Django 3.0.7 on 2020-06-22 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200622_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ampoules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('product_id', models.IntegerField(db_index=True)),
                ('recipe', models.CharField(max_length=255)),
                ('batch_number', models.IntegerField(blank=True, null=True)),
                ('batch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('inspected', models.IntegerField()),
                ('accepted', models.IntegerField()),
                ('rejected', models.IntegerField()),
                ('technical_rejects', models.IntegerField()),
            ],
        ),
    ]
