# Generated by Django 3.0.7 on 2020-07-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20200708_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ampoule',
            name='st0_height',
        ),
        migrations.RemoveField(
            model_name='vial',
            name='st0_height',
        ),
    ]
