# Generated by Django 3.0.7 on 2020-08-09 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200708_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampoule',
            name='batch_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vial',
            name='batch_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
