# Generated by Django 3.0.7 on 2020-06-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_ampoules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ampoules',
            new_name='Ampoule',
        ),
    ]
