# Generated by Django 3.0.7 on 2020-08-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200809_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampouleaudit',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=555, null=True),
        ),
        migrations.AlterField(
            model_name='vialaudit',
            name='description',
            field=models.CharField(blank=True, db_index=True, max_length=555, null=True),
        ),
    ]
