# Generated by Django 3.0.7 on 2020-06-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20200622_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='VialAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordID', models.IntegerField(db_index=True)),
                ('TimeStamp', models.DateTimeField()),
                ('DeltaToUTC', models.IntegerField()),
                ('UserID', models.CharField(blank=True, max_length=255, null=True)),
                ('ObjectID', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=555, null=True)),
                ('Comment', models.CharField(blank=True, max_length=255, null=True)),
                ('Checksum', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
