# Generated by Django 3.0.7 on 2020-06-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_vialaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vialaudit',
            name='DeltaToUTC',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
