# Generated by Django 3.1 on 2020-09-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20200813_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='ampoule',
            name='filename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='ampouleaudit',
            name='filename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vial',
            name='filename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='vialaudit',
            name='filename',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
