# Generated by Django 3.1 on 2020-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20200920_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ampoule',
            name='filename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='ampouleaudit',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='vial',
            name='filename',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='vialaudit',
            name='filename',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
