# Generated by Django 3.0.7 on 2020-06-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20200625_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vialaudit',
            name='TimeStamp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
