# Generated by Django 3.0.7 on 2020-06-25 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20200625_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmpouleAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecordID', models.CharField(blank=True, max_length=255, null=True)),
                ('TimeStamp', models.CharField(blank=True, max_length=255, null=True)),
                ('DeltaToUTC', models.CharField(blank=True, max_length=255, null=True)),
                ('UserID', models.CharField(blank=True, max_length=255, null=True)),
                ('ObjectID', models.CharField(blank=True, max_length=255, null=True)),
                ('Description', models.CharField(blank=True, max_length=555, null=True)),
                ('Comment', models.CharField(blank=True, max_length=255, null=True)),
                ('Checksum', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
